# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.network "forwarded_port", guest: 27017, host: 27017

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y mongodb
    sed -i "s/^bind_ip.*$/#bind-ip = 127.0.0.1/" /etc/mongodb.conf
    systemctl restart mongodb
    #sudo -u postgres psql -c "alter user postgres with password 'secret';"
  SHELL
end
